samtools/htscodecs

javascript/tok3.js

Minor fix in name tokenizer code (I get syntax errors without this change).

Fix missing exception variable in catch block in tok3.js.

---

htscodecs/rANS_static.c

The warning is issued by some versions of clang (notably the one Travis uses for Mac builds).  The extra braces aren't strictly
necessary, but adding them is harmless and makes builds using -Werror work.
For an example of the warning, see https://travis-ci.com/github/samtools/htscodecs/jobs/453582092

Silence "suggest braces around initialization" warning

---

.gitignore

Not needed for htscodecs itself, but it's handy for htslib which wants to build parts of htscodecs in a submodule, and makes separate PIC and non-PIC object files.

Make git ignore .pico files

---

htscodecs/rANS_static4x16pr.c
htscodecs/tokenise_name3.c

This is independent from the OSS fuzzing and doesn't need to be applied for those, hence a separate PR. (Ignore my branch name! It does fix 29796 but for the wrong reason.)
This is set to about 15Gb.  It's still high, but it prevents the most
egregious excesses.  The purpose is simply to prevent malformed data
from requesting obscene amounts of memory (although in theory that may
still be possible if the caller is also doing multi-threading).
That's equivalent to 10 million records in a block.  1 million may be
more reasonable, but it's also something I've used in extreme cases so
if feels to close to proper usage to limit it at that value.
Detected while looking at OSS-Fuzz 29796, but this isn't that bug
(which has already been fixed elsewhere).

Add an arbitrary maxname on the name tokeniser.

---

htscodecs/rANS_static4x16pr.c

Now F[] is unsigned, it can never be less than zero.  This upsets older versions of clang.

Remove unnecessary comparisons

---

htscodecs/rANS_static.c
htscodecs/tokenise_name3.c

Google fuzzer identified this in tokenise_name3.c.
The rANS_static.c change was found looking for others via grep.  I'm
unsure if it's possible to trigger (although it seems likely) and if
so why it hasn't been found yet, but protecting it too just incase.
Fixes oss-fuzz 29956

fix undefined shift.

---

htscodecs/rANS_byte.h
htscodecs/tokenise_name3.c

- Protect against no tokens present in tok_name3 codec.
Fixes oss-fuzz 30008
- Fix undefined shift in rANS_byte.h
(I thought I'd grepped for all of these, but didn't think the look
in the header files.)
Fixes oss-fuzz 30017

Fix more fuzzing found issues.

---

htscodecs/rle.c

Fixes oss-fuzz 30381
Fixes oss-fuzz 30395

Fix off-by-one error in array bounds checking.

---

tests/arith.test
tests/fqzcomp.test
tests/rans4x16.test
tests/rans4x8.test
tests/tok3.test

On macOS the shell's builtin `echo` doesn't process options in some circumstances, resulting in
```
-n Testing arith_dynamic [...]
11615
```
as can be seen in [HTSlib macOS CI build logs](https://cirrus-ci.com/task/4839257728614400).
Using `printf(1)` is (sadly) overall more portable.

Use printf in shell scripts instead of echo -n

---

htscodecs/tokenise_name3.c

If a delta operation, DDELTA, DDELTA0 or MATCH then it needs to
validate that we've not gone beyond the number of tokens used in the
previous name.
This can even trigger on the very first read, so we need to make sure
we also initialise the first name last_ntok too (pnum==cnum==0 for
first name).
Fixes oss-fuzz 31210
Fixes oss-fuzz 31215

fix access of uninitialise memory in decode for name tokeniser.

---

tests/fqzcomp.test

This fails with `awk: record 'S9$#6#6%7654A5634A;$...' too long` on Solaris/OpenIndiana's `awk`. We could configure around this to use `nawk` on this platform instead (as in PR samtools/samtools#1165, but more complicated due to needing to transmit the setting from htslib as well), but in this case it's easier to just use `cut`.

Fix spurious test failure on Solaris/OpenIndiana

---

htscodecs/tokenise_name3.c

If delta is zero (as it is for the first record) and we make use of something that does differencing to the previous record, then pnum == cnum and we query ctx->lc[pnum].ntok before setting ntok at the end of the loop.
Fixes oss-fuzz 32688

Fix an uninitialised access in the name tokeniser decode.

---

htscodecs/tokenise_name3.c

If the number of names increases by exactly 1 between successive slices, and the old value was the size of our allocated buffer, then we don't grow it by one.  This causes the last decoded name to return -1 instead of 0 as we do the max_names check before doing t0 < 0, which in turn gives a failure to decode slice error message.
It could be fixed in two ways, by shifting where the end of names check happens, or fixing the allocation.  I chose the latter as it would take more head scratching to determine why the allocation has `++max_names` in it.

Fix a bug with name tokeniser and variable number of names per slice.

---

configure.ac
m4/ax_with_libdeflate.m4
m4/zlib.m4

Avoid warnings about obsolete usage from `autoreconf`:
```
configure.ac:73: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:73: You should run autoupdate.
configure.ac:93: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:93: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:111: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:119: warning: AC_OUTPUT should be used without arguments.
```
The most recent “new” autoconf feature in this change is from 2.59 in 2006. `LT_INIT` has sufficed for libtool for even longer.

Modernise autoconf usage

---

MAINTAINERS.md
NEWS
README.md
configure.ac
htscodecs/htscodecs.h

The only change is updating the HTSCODECS_VERSION macro in htscodecs.h
also.  I forgot to do this for 1.1, so this is a tiny change.  (The
NEWS file just glosses over the existance of 1.1 and jumps straight to
1.1.1.)
My apologies.
Also added a MAINTAINERS.md file as an aide memoir for future releases.

Update to release 1.1.1

---

htscodecs/c_range_coder.h

This meant the most naive of small tests would fail to decode as the compressed data size exactly consumes the size of the initialisation of `rc->code`.  We incorrectly rejected this case.
Note this also shows a weakness of error reporting, as the caller needs a better way to be told of the input data being too small (which admittedly it wasn't, but the bug meant it thought it was but no report was given).
That's a much wider change, for another PR some time, as it'll need the error handling in c_simple_model.h completely redesigning.

Fix off-by-one error on initial size check for arith_dynamic.

---

htscodecs/rANS_static4x16pr.c
htscodecs/rANS_word.h
htscodecs/rle.c
htscodecs/utils.h

A mixture of bits cherry-picked out of the unroll32 branch.  These apply to the main codecs and not just the 32-way SIMD implementation.  Some perf stat reports from 10 runs on low complexity (q4) and high complexity (q40) data sets comparing master (old) vs this PR (new).
Clang10
```
Giga-cycles enc     Giga-cycles dec
old      new        old      new
4x8 -o1 q4          2186     2061 -     1225     1202 -
4x8 -o1 q40         1570     1482 -     1033     1034 ~
4x16 -o193 q4       1533     1435 -      778      762 -
4x16 -o1 q40        2553     1789 --     863      868 ~
```
Gcc11
```
Giga-cycles enc     Giga-cycles dec
old      new        old      new
4x8 -o1 q4          2174     2075 -     1234     1205 -
4x8 -o1 q40         1667     1574 -     1045     1045 =
4x16 -o193 q4       1694 …
```

Various rANS speedups

---

.cirrus.yml
htscodecs/fqzcomp_qual.c

An array of 128x8 = 1024.
This is RLE as 128, 128, x6
At z=256 z+128*6=1024, so this needs to be z<=size instead.
It meant some lookup tables weren't decodable.
Also included the same cirrus CI fix we applied to samtools et al (centos -> rocky)

Bug fix to bounds checking in fqzcomp read_array.

---

htscodecs/tokenise_name3.c

The uncompress function didn't reset the uncompressed size (making the
subsequent assert pointless), instead trusting the recorded 'ulen'
size as real. If data uncompressed to a smaller amount, it meant parts
of the buffer were uninitialised, triggering an uninitialised memory
read.
Now this is fixed, we hit asserts, which isn't good either.  So that's
now a proper error return instead.

Fix a fuzzing test failure in tokenise_name3.

---

htscodecs/arith_dynamic.c
htscodecs/fqzcomp_qual.c
htscodecs/rANS_static4x16pr.c
htscodecs/tokenise_name3.c

* Use consistent data types in `rans_compress_bound_4x16()`
* Reject stripe mode inputs with zero stripes, preventing an endless loop in `unstripe()`
* Fix UBSAN warnings about operations on NULL pointers, decoding bit-packed or RLE data.
* Reject attempts to duplicate non-existent name tokeniser streams.
* Fix possible use of uninitialised memory in rans_uncompress_O1_4x16().
The first three commits have been pulled over from #26, as they fix pre-existing bugs unrelated to the other updates there.

Assorted bug-fixes

---

htscodecs/rANS_static4x16pr.c
tests/benchmark.sh

Removed a warning introduced in #43.  Also fixed broken indentation that appeared then too.
A subsequent PR will land to change everything to spaces, to avoid non-standard tab configurations leading people up the garden path.  (To my mind, the only valid definition of a tab is the one used as standard by unix terminals, as that permits people to view source outside of a particular editor.)

SIMD tidy up

---

htscodecs/rANS_static4x16pr.c
htscodecs/utils.h

hist8e() in utils.h attempted to use it if __GNUC__ was not defined, but it was a static function in rANS_static4x16pr.c so not exported.  Simple solution is to make it a static inline in utils.h instead.

Move fast_log to htscodecs/utils.h

---

htscodecs/rANS_static4x16pr.c

Windows versions of Intel ICX (based on clang) don't define __GNUC__.
Suggested fix reported by Eugene Shelwien.

Small tweak to compiler detection.

---

htscodecs/rANS_static32x16pr_avx2.c
htscodecs/rANS_word.h

I'm not sure why I ever had the manual pointer arithmetic in the first place for syms[] / syms[][], but doing it the sensible way is actually a bit faster with some gccs too (about 12% faster encode for gcc 7.5 on ubuntu 18.04).

Fix more aliasing issues with rANS codec.

---

configure.ac
htscodecs/Makefile.am

The first commit here improves the configure checks for compiler options like `-mavx512` by adding test source code.  It makes the tests less likely to be defeated by compilers that accept the `-m` option, but don't really support it.
The second fixes warnings about empty translation units from the MacOS linker, and `gcc` when using `-pedantic`.  It uses [`AM_CONDITIONAL`](https://www.gnu.org/software/automake/manual/html_node/Conditional-Sources.html) to remove any source files that would be empty following the results of the configure run.
The third changes how compiler options are set for the object files that require specific SIMD flags.  This was done using target-specific variables, which are only supported by GNU make.  They are removed, and replaced with the [automake way of doing …

Configure and automake improvements

---

htscodecs/rANS_byte.h
htscodecs/rANS_static.c
htscodecs/rANS_static32x16pr.c
htscodecs/rANS_static4x16pr.c
htscodecs/rANS_word.h
htscodecs/utils.h
tests/rANS_static4x16pr_test.c

The changes are a combination of likely / unlikely macros and some
code structure tweaking after extensive profiling with different
compilers on low and high-entropy data.
It's almost impossible to gain speed in all cases, and optimisations
like this usually favour one system over another.
On a modern intel system (Xeon(R) Gold 6142), a few specific compiler
versions and optimisations had issues before.  The main winners are
rans4x8 clang13 -O3 encode and gcc11 / gcc12 decodes (both 4x8 and
4x16), both often by 10-20% faster.  The biggest loss is rans4x8 clang
7.0 encode, by 5-7% slower.
On an older Intel (Xeon E5-2660), the loser is clang 10.0 rans4x8,
which is up to 5% slower.  The biggest wins are rans4x8 decode, on a
mix of compilers: gcc 7, 10, 11 and all clang.

Various speed improvements to rANS codecs.

---

htscodecs/arith_dynamic.c
htscodecs/fqzcomp_qual.c
htscodecs/rANS_static.c
htscodecs/rANS_static16_int.h
htscodecs/rANS_static32x16pr_avx2.c
htscodecs/rANS_static32x16pr_avx512.c
htscodecs/rANS_static32x16pr_neon.c
htscodecs/rANS_static32x16pr_sse4.c
htscodecs/rANS_static4x16pr.c
htscodecs/tokenise_name3.c
tests/arith_dynamic_test.c
tests/entropy.c
tests/fqzcomp_qual_test.c
tests/rANS_static4x16pr_test.c
tests/rANS_static_test.c
tests/tokenise_name3_test.c

(We still have a limit of >2GB though)
Reported by Divon Lan

Fix compression of data blocks close to 2GB in size.

---

NEWS.md
htscodecs/arith_dynamic.c
htscodecs/rANS_static4x16pr.c

The meta-data is 2 bytes for order + N, ? bytes for original size, and
`4*N` bytes for the N compressed sizes.  We forgot about the original
size so only left room for `2+5*N` (with 5 being the maximum size of a
32-bit var int).  So blocks larger than 2^28 risked not fitting in the
allocated meta-data size.
Reported by Divon Lan.

Fix bug with RANS_ORDER_STRIPE on large blocks.

---

configure.ac
htscodecs/rANS_static32x16pr_avx2.c
htscodecs/rANS_static32x16pr_avx512.c
htscodecs/rANS_static32x16pr_sse4.c
m4/ax_check_compile_flag.m4

On this platform _mm256_extract_epi64 isn't defined, but the rest of
AVX2 is.  It needs to fail auto-detection.
Also we get unaligned accesses in the SSE4 code with tbuf due to
differing data alignment caused by 32-bit pointers instead of 64-bit.
This exposes an underlying problem of using aligned SIMD writes on
tbuf without explicitly asking for alignment. (The new code is also
sometimes a little faster.)
See also samtools/htslib#1500

Improvements for intel -m32 builds.

---

htscodecs/rANS_static.c
htscodecs/rANS_static16_int.h
htscodecs/rANS_static32x16pr.c
htscodecs/rANS_static32x16pr_avx2.c
htscodecs/rANS_static32x16pr_avx512.c
htscodecs/rANS_static32x16pr_neon.c
htscodecs/rANS_static32x16pr_sse4.c
htscodecs/rANS_static4x16pr.c
htscodecs/utils.c
htscodecs/utils.h
tests/entropy.c

While building htscodecs on FreeBSD, I found that most of the tests were failing due to a segfault in `htscodecs_tls_free()` due to `tls` being NULL. After much debugging, it turned out that `pthread_once()` was not working and `htscodecs_tls_init()` was never called.
Checking the return code from `pthread_once()` and printing a diagnostic provides a chance to diagnose this situation quickly rather than just being presented with the eventual segfault.
It turns out that on FreeBSD if you neglect to link with `-lpthread` or `-lthr`, libc provides versions of the pthread functions including a [`pthread_once()` stub that just doesn't work](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=150959). So the cause of these test failures was neglecting to link with `‑lthr` or another threading …

Check pthread_once() return value and print diagnostic

---

configure.ac
m4/ax_search_libs_rev.m4

Implemented an AX_SEARCH_LIBS_REV function as a minimal replacement of AC_SEARCH_LIBS but with the no-library case as the last thing to try. This solves the problem where we preferentially want an external library implementation over the built-in C library.
Addresses autoconf issue raised in #64

Improve checks for pthread calls on FreeBSD

---

htscodecs/arith_dynamic.c
htscodecs/pack.c
htscodecs/rANS_static4x16pr.c

Previously when too many symbols were present, we still returned packed data but with 1 byte per symbol.  It was then up to the caller to reject this as inappropriate use of pack.  This meant that hts_pack was a transparent transform that always gives back something even if it's actually just growing the data by 1 byte.
However the CRAMcodecs spec states this scenario is illegal.
The checks in rANS_static4x16pr.c were bugged for nsym==256 as there wasn't a check of "|| out[c_meta_len] == 0", but now it's a moot point as NULL will be returned.
Fixes #65

Update hts_pack to operate in line with the spec.

---

htscodecs/rANS_static32x16pr.c
htscodecs/rANS_static32x16pr_avx2.c
htscodecs/rANS_static32x16pr_avx512.c
htscodecs/rANS_static32x16pr_neon.c
htscodecs/rANS_static32x16pr_sse4.c
htscodecs/rANS_static4x16pr.c

The 4x16 O1 decoder can do compression of the O1 frequency table. When it decoded this it was meant to ensure we have at least c_freq_sz bytes (size of compressed table) + 16 (4 4-byte rANS states).  However "at least" was implemented as "more than" due to a > vs >= error.
However on further inspection the code after this has an additional check for at least 16 bytes of rANS state anyway so the freq table check didn't need the 16 there at all.  This was good as it was still 16 for the 32-way decoder, which again was checked, correctly, later on.
Reported by Divon Lan

Remove overly aggressive buffer overflow checking in rans O1 decoder

---

htscodecs/tokenise_name3.c

When arithmetic mode is enabled, we now also try the bz2 backend to arith, post any pack/rle.
Also refactored the code to cache the best result and return it rather than hte best method and recalculate it.  This is a significant speed increase, helping to offset the extra cost in tok3 -17/-19.
Finally, to offset the reduced compute cost, -5 and -15 have a slight tweak to methods to offer a smoother transition of speeds.
Aggregate benchmarks with a mix of ~12 mill read names from many vendors and instrument models.
```
OLD             NEW
sec  byte       sec  byte
1       1.70 6053051    1.63 6053051
3       1.91 4925224    1.72 4925224 <-- default in CRAM 3.1
5       3.01 4815078    2.84 4781855
7       4.58 4755225    3.97 4755225
9       4.88 4754659    4.29 4754659
11      3.21 5999169 …
```

Add arith+bzip2 support to name tokeniser

---

tests/arith_dynamic_fuzz.c
tests/arith_dynamic_test.c
tests/entropy.c
tests/fqzcomp_qual_fuzz.c
tests/fqzcomp_qual_test.c
tests/rANS_static4x16pr_fuzz.c
tests/rANS_static4x16pr_test.c
tests/rANS_static_fuzz.c
tests/rANS_static_test.c
tests/tokenise_name3_fuzz.c
tests/tokenise_name3_test.c
tests/varint_test.c

This helps pick up things like XOPEN_SOURCE definitions as required.
This is a less icky solution to the one in https://github.com/samtools/htslib/issues/1608, although it still needs to explicit `-D_POSIX_C_SOURCE=200112L` makefile definitions removing.

Add include of config.h to test programs.

---

.cirrus.yml

A basic config, but does the minimum necessary for testing.

Add FreeBSD to the CI tests

---

htscodecs/rANS_static4x16pr.c
tests/rANS_static4x16pr_test.c

- Favour AVX2 over AVX512 for some rans combinations on AMD.  This may need changing again later, but this is a simple fix for now.
- Move cpu checking capabilities to a once-per-thread set of static globals, to avoid overhead.
- Added block-size adjustments to rans4x16pr test harness.  It's not there for other codecs, but could be easily added.

Amd avx512

---

tests/rANS_static4x16pr_test.c

If we have uncompressible data with size almost BLK_SIZE, then the compressed size gets larger than BLK_SIZE (ie the meta-data to indicate "CAT" mode).
This in turn triggers an incorrect overflow check in the decode part of test main(), which needed to check against allocated buffer size rather than BLK_SIZE.
This had no impact on the library, just the CLI test tool.

Trivial bug fix to tests/r4x16pr demo.

---

htscodecs/varint.h

Constant needs to be unsigned for the shift to work portably. Strictly only the last one needs to be fixed for UBSAN, but we may as well make them all consistent.

Fix illegal shift complaint from UBSAN

---

htscodecs/rANS_static16_int.h
htscodecs/rANS_static4x16pr.c

Fix ARM compilation with certain Conda compilers
A broken conda config removed HWCAP_ASIMD definition.  It's fixed now,
but we check with ifdefs as suggested by John Marshall in comments on
the issue.
Hence code is buildable, just minus NEON support on specific OS and
hardware combinations.
Also a minor tweak to remove an assert related warning.

Fix ARM compilation with certain Conda compilers

---

htscodecs/arith_dynamic.c
htscodecs/c_range_coder.h
htscodecs/fqzcomp_qual.c
htscodecs/tokenise_name3.c
tests/tokenise_name3_test.c

Fixes a couple buffer overruns during encode in fqzcomp and name tokeniser.  Both codecs are primarily fuzzed with random input for decode, but encode matters a lot too.
The fqzcomp code failed when given an extreme case of 1 million 1bp reads.  The code incorrectly computed the worst case expansion by failing to account for (mainly) the 2-bits of average quality across the reads.  This has been fixed both in a revised buffer growth, but also by adding proper bounds checking to the range coder.
The name tokeniser failed when hitting 128 tokens due to a lack of checks in the encoder.  Could be triggered by a read name of 128 # symbols.
Thanks to @shubhamchandak94 for the bug report.

Chandak overflow

---

htscodecs/rANS_static32x16pr_sse4.c

Specifically, the SIMD decoder handles this case, but the tidyup code at the end for any remainder of < 32 bytes to go didn't.
Triggered by the follow example:
perl -e 'print "\0"x0xff0,"AAABAA\0"'|./tests/rans4x16pr -t -o5 -c 0x0201

Fix an overflow with freq=4096 in the SSE4 decoder.

---

htscodecs/rANS_static.c
htscodecs/rANS_static4x16pr.c
tests/arith_dynamic_test.c
tests/rANS_static4x16pr_test.c
tests/rANS_static_test.c

When given 0 bytes of input, we get a floating point exception in the code attempting to renormalise the frequencies.
The test harness can't trigger this case as 0 is EOF in the read loop, but that has been changed so a null file still calls the compression. Also tested the other entropy encoders, but they already coped fine.
Bug reported by Shubham Chandak

Remove divide by zero in rANS 4x8.

---

NEWS.md
configure.ac
htscodecs/htscodecs.h

Note although we have added a single new API in c_range_coder.h, this file is entirely static inline functions so it does not have implications on library ABI version compatibility.

Updates for 1.5.2 release

---

htscodecs/tokenise_name3.c

Replace aborts with returns.  Also be consistent in signed vs unsigned char behaviour when looking for non-7-bit ASCII.
Fixes #105

Name tokeniser fixes.

---

htscodecs/tokenise_name3.c

We were one byte too short on our bounds checking, which meant a serialised data stream that ended with a duplicate token failed the "o+2 >= sz" check.
This could be reproduced with a pair of names "00x\n12\n".

Fix tok3 decode bounds checking.

---

.gitignore
htscodecs/fqzcomp_qual.c
htscodecs/rANS_static4x16pr.c
tests/Makefile.am
tests/entropy.c
tests/entropy_fuzz.c
tests/fqzcomp_qual_fuzzrt.c
tests/tokenise_name3_fuzzrt.c

- Fix rans_set_cpu to work a second time.  This only really matters for test/entropy.
- Add a test/entropy_fuzz.c  (@daviesrob you'll want this commit as it has the Makefile work, but you may want to edit the entropy_fuzz.c file itself.  Mine is just a copy of entropy.c, which is working and finding bugs)
- Fix the rans_set_cpu to once again support different CPU types for encoder and decoder.  We do test every codec, but we accidentally lost this ability to have half and half, which affected cross-validation between codecs.
- Small typo fix in entropy.c where it wasn't using RLE+PACK+SIMD.

A mixture of fuzz-testing improvements

---

README.md
htscodecs/rANS_static16_int.h
htscodecs/rANS_static32x16pr_avx2.c
htscodecs/rANS_static32x16pr_avx512.c
htscodecs/rANS_static4x16pr.c

Also incorporates the old #92.
Intel Downfall / GDS security flaw caused the issue of an updated microcode to mitigate the problem.  Unfortunately the consequence of this is that SIMD gather instructions are now considerably slower, particularly AVX2.  So much so that it turns out saving the SIMD register to memory, using traditional scalar code to do the memory fetches one at a time and then loading those scalar fetches back into the SIMD register, is *considerably* faster than the AVX2 gather microcode instruction.  The mind boggles, but there we are.  As it turns out I was already exploring these sort of things for AMD Zen4 too as that has (had) a far slower gather instruction than Intel.
We could do on-the-fly measurements and work out how far the gather is, so we know whether to use …

Downfall mitigation via simulated gathers

---

htscodecs/tokenise_name3.c

The names "012345a" and "123456" have token 0 type as N_DIFF (standard delta to previous name) and token 1 DIGITS0 with DZLEN 6.  N_DIFF is type 6, so we get 6,6 for first stream and 6,6 for the tok1 DZLEN stream.   This then gets labelled as a dup of stream #0.
Unfortunately our "dup_from" flag is 0 for non-dupped and >0 for dup vs stream X.  This meant the data written was incorrect, giving data we couldn't decode.

Fix tok3 encoding bug with duplicated streams.

---

htscodecs/rANS_static32x16pr_sse4.c

There was a -DUBSAN guard for use with undefined behaviour sanitizers, but actually the only code change that's necessary is to change the explicit writes to a memcpy.  This fixes unoptimised zig-cc builds which use -fsanitize=undefined by default.
I've tested gcc7, gcc13, clang10, clang16, zig cc, icc and icl.  All seem fine with this change.
NB: Zig cc is the only on to vectorise the most naive implementation, and it does so very well, basically creating an SSE4 version of the loop. That is the even fastest implementation for zig cc.

Remove undefined behaviour in transpose_and_copy.

---

configure.ac
htscodecs/Makefile.am
m4/hts_check_compile_flags_needed.m4

Zig adds native support for the CPU being built on.  So if we support popcnt then we don't need an explicit -mpopcnt.  However adding any -m options appears to disable that native support, so -mavx2 doesn't enable -mpopcnt, yet our auto-detection previously claimed it was necessary.  This means building on a CPU with popcnt but no avx2 will fail to build (with zig) when targetting the avx2 platform.
Therefore the only reliable way to check is the combinations actively in use.  So if we want to compile code using popcnt + avx2 then we have to test -mpopcnt -mavx2 together.
It's problematic and tricky to manage in autoconf.
Fixes #109

Add explicit -mpopcnt to avx2 and avx512 builds.

---

htscodecs/rANS_static32x16pr_avx512.c

Minor adjustment for old, but still supported, RedHats.

Allow builds on old gcc's that don't like declarations in for loops

---

configure.ac
htscodecs/rANS_static4x16pr.c

Fixes #115.
Testing compiler versions is tricky, especially given some vendors wrap up standard compilers as their own, but change version numbers (Apple, Intel) and compilers also often masquerade as another (eg setting GNUC).
Instead we just check if it links.  Note there's no guard around this here for x86-64, but that's done in the code itself.  (In theory we may have cpuid on another architecture that we wish to use at some point.)

Add cpuid checks behind an HAVE_CPUID check.

---

configure.ac

Some compiler installations (notably xcode for MacOS El Capitan) are missing some of the avx512f intrinsics.  As these were not specifically checked for in configure, it enabled avx512 but builds failed due to the missing symbols.  Fix by adding some extra lines to the avx512f configure test so it can turn avx512 off on these platforms.
Part of fix for samtools/htslib#1773

Test for more avx512 functions

---

htscodecs/rANS_static4x16pr.c

Since 6dadc2a8d42d4d101b0bc96807147fce96fe0ddf / samtools/htslib#1628, this code is compiled with `_XOPEN_SOURCE` set, usually to 600.
Setting this causes FreeBSD's `<sys/types.h>` not to define these old BSD-style typenames such as `u_long`. Happily we can just write it out as the corresponding native type — fortunately [`u_long`'s definition](https://cgit.freebsd.org/src/blame/sys/sys/types.h#n48) has not changed in 30+ years…

Avoid disabled typedef in FreeBSD-specific code

---

htscodecs/tokenise_name3.c

On linux these tables are 384 wide, to accommodate -128 to +255. However this is an implementation defined security improvement and the specification is such that the parameter to e.g. isalpha should be unsigned.
Detected with the stock windows gcc install (mingw-w64 didn't complain).
See https://github.com/samtools/htscodecs/pull/123#discussion_r1662357349 for background.

Use unsigned chars for ctype macros.

---

htscodecs/arith_dynamic.c
htscodecs/rANS_static4x16pr.c
htscodecs/tokenise_name3.c

These should be set to a minimum of at least rans_compress_bound_4x16() or arith_compress_bound()  but as they're user supplied parameters we ought to consider the possibility of them being smaller and the potential for an encode failure.  (Although arguably it's a user error too as we're not using the API as intended.)
This happens in many places, but not consistently when very small sizes are given such that we don't have room for the compression header meta-data.

Improve checking of *out_size in rans4x16 & arith

---

.cirrus.yml

See https://cirrus-ci.org/guide/FreeBSD/ for the valid image names.

Change the version of FreeBSD for cirrus-ci to 14.1

---

.cirrus.yml
.github/workflows/unix-build.yml

Followup to PR #129 — The freebsd-org-cloud-dev GCP project has now dropped freebsd-14-1-*. See also <https://cirrus-ci.org/guide/FreeBSD/> and its suggested `gcloud compute images list …` command.

Bump CI FreeBSD image_family again, to 14.2

---

NEWS.md
configure.ac
htscodecs/arith_dynamic.c
htscodecs/htscodecs.h
htscodecs/rANS_static4x16pr.c

Minimal changes - some memory checking bug fixes and then it's mostly CI issues.  However making a release so we can have an official version to include in Htslib (which makes upstream package managers happier).

Make release 1.6.2

---

NEWS.md
configure.ac
htscodecs/htscodecs.h
htscodecs/rANS_static4x16pr.c

I clearly need to improve the test harness to do things that are erroneous / don't fit, as somehow htslib is testing this code path.  It turns out #127 had a memory leak in it when recovering from rans encoding failure.
This PR doesn't add those tests, but it's noted for something I need to fix later.

Rans4x16 frees and release v1.6.3

---

htscodecs/rANS_static4x16pr.c

This fixes a thread data access race on the first time through the function, although it's pretty harmless as a consequence of the race is we may provide a optimal codec implementation.

Move the pthread_once call earlier in rans_enc_func / rans_dec_func.

---

htscodecs/tokenise_name3.c

1.  UUID4 improvements.
With this change on my local corpus:
```
htscodecs-corpus/names/01.names     169625
htscodecs-corpus/names/02.names     417607
htscodecs-corpus/names/03.names     49868
htscodecs-corpus/names/05.names     288460
htscodecs-corpus/names/08.names     42594
htscodecs-corpus/names/09.names     255867
htscodecs-corpus/names/10.names     307270
htscodecs-corpus/names/20.names     139707
htscodecs-corpus/names/_139.names   86966   *
htscodecs-corpus/names/_shuf.names  638699  *
htscodecs-corpus/names/nv.names     329535
htscodecs-corpus/names/nv2.names    87802
htscodecs-corpus/names/rr.names     91103
htscodecs-corpus/names/uuid4+.names 153556  *
htscodecs-corpus/names/uuid4.names  153439  *
```
Master:
```
htscodecs-corpus/names/01.names     169625 …
```

UUID4 name tokeniser plus improvements to mixed data sets.
